{
 "title": "Overall",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connexions",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fff\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logins.logs\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Incident pod",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fff\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SF_Incident\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IsError\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Total Licences",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r.type == \"Licenses\" and r._field == \"Total\")\r\n\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._field == \"last update\")\r\n\r\n    "
    }
   ]
  },
  {
   "title": "Remains Licences",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r.type == \"Licenses\" and r._field == \"Remains\")\r\n\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "title": "Current Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"OrgInformation\" and r.type == \"OrgInformation\" and r._field == \"Pod\")\r\n    |> limit(n: 1)\r\n\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"fff\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SF_Incident\")\r\n"
    }
   ]
  },
  {
   "title": "Total Licences",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r.type == \"Licenses\" and r._field == \"Total\")\r\n\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "title": "Health Security Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"SecurityHealthCheckScore\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"Score\")\r\n    |> filter(fn: (r) => r[\"type\"] == \"Security\")\r\n    |> limit(n: 1)\r\n\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "title": "Licenses Avalable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r.type == \"Licenses\")\r\n    "
    },
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"license\" and r._field == \"TotalLicenses\" and r.type == \"Licenses\")"
    }
   ]
  },
  {
   "title": "Daily Limits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and r._field == \"UsedPercent\" and r.type =~ /Daily/)\r\n    |> aggregateWindow(every: 20m, fn: mean, createEmpty: false)\r\n    |> yield(name: \"mean\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "File Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and (r._field == \"Remaining\" or r._field == \"Done\" ) and r.type == \"FileStorageMB\" )\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"OrgInformation\" and r.type == \"OrgInformation\" and r._field == \"releaseVersion\")\r\n    |> limit(n: 1)\r\n\r\n    "
    }
   ]
  },
  {
   "title": "Next Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"OrgInformation\" and r.type == \"OrgInformation\" )\r\n    |> limit(n: 1)\r\n\r\n    "
    }
   ]
  },
  {
   "title": "PermSet",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and (r._field == \"Remaining\" or r._field == \"Done\" ) and r.type == \"PermissionSets\" )\r\n"
    }
   ]
  },
  {
   "title": "API Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and r._field == \"Done\" and r.type == \"DailyApiRequests\")\r\n    |> aggregateWindow(every: 20m, fn: mean, createEmpty: false)\r\n    |> yield(name: \"mean\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Single Email",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and (r._field == \"Remaining\" or r._field == \"Done\" ) and r.type == \"SingleEmail\" )\r\n"
    }
   ]
  },
  {
   "title": "sObject Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -2h)\r\n    |> filter(fn: (r) => r._measurement == \"CountRecords\" and r[\"_field\"] == \"size\" and ( r[\"type\"] == \"Account\"\r\n    or r[\"type\"] == \"Contact\" or  r[\"type\"] == \"Calendar\" or r[\"type\"] == \"Event\" ))\r\n    |> sort(columns: [\"_value\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Data Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and r._field == \"Done\" and r.type == \"DataStorageMB\" )\r\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"fff\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"SecurityHealthCheck\" ) \r\n  |> limit(n: 1)"
    }
   ]
  },
  {
   "title": "Data Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fff\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"limits\" and r._field == \"UsedPercent\" and r.type == \"DataStorageMB\" )\r\n"
    }
   ]
  }
 ]
}